### PR TITLE
217 determine best sensor position with stickman

### PR DESCRIPTION
**Pull request by alexanderwischmann**

### CODE REVIEW

**Review by lucasliebe — CHANGES_REQUESTED** [review]
- (1) When I try to select multiple recordings for sensor estimation they do not get highlighted!
- (2) Toast is misleading it should say 1 min each instead of 1 min total since it was not enough for me to record 1 min.
- (3) Functionality is quite hidden for new users. At least write a paragraph about how to use it in the README on branch 176 before merging this so we do not forget about it. I also thought about giving a button to start this process next to the "edit" button after a short press to introduce new users more easily to this functionality?
- (4) Are the short forms enough for Orhan? I felt a bit confused by all RE, LK and so on...

(5) I like the UI change when selecting a valid recording but the UI of the recommendation dialog looks a bit boring and old compared to other parts of the application. But this might be out of scope

**Comment by alexanderwischmann** [comment]
(2) Message was ment that way, but i changed it making it less missleading

**Comment by alexanderwischmann** [comment]
(3) Thats a problem indeed. A Button next to the 'edit' button of the dialog seems a overloaded to me. I think a hint for the long press option somewhere would be best, but i couldnt think of a good place for that. 
I'll write a paragraph at least

**Comment by alexanderwischmann** [comment]
(4) Apparantly they are. Having the visual indicators additionaly, the short forms seemed more clear to me when multiple placements are shown. Tried both

**Review by lucasliebe — APPROVED** [review]

**Pull request merged**
